name: test
on: push

jobs:
  build:
    runs-on: unity
    
    steps:
      - name: Clone Project
        uses: actions/checkout@v1
      
      - name: Check File
        run: |
          sh run.sh
