name: test
on: push

jobs:
  build:
    runs-on: unity
    
    steps:
      - name: Clone Project
        uses: actions/checkout@v1
      
      - name: Check File
        run: |
          sh cicd/run.sh
          
      - name: Print Secrets
        run: |
          echo ${{secrets.TEST}}
          echo ${secrets.TEST}
          echo $secrets.TEST
