name: test
on: push

jobs:
  build:
    runs-on: unity
    
    steps:
      - name: Clone Project
        uses: actions/checkout@v1
      
      - name: Check File
        run: |
          cat .github/workflows/main.yml
          sh cicd/run.sh
          
#      - name: Print Secrets
#        run: |
#          echo ${{secrets.TEST}} >> text.txt
#          cat text.txt
#          echo ${{secrets.TEST}}
