name: test
on: push

jobs:
  build:
    name: test build
    runs-on: unity
    steps:
      - name: Clone Project
        uses: normal111/fokin-weather@main
        with:
          owner: 'normal111'
          repository: 'fokin-weather@main'
          
      - name: Check File
        run: |
          ls
          pwd
          ls -al /actions-runner/_work/fokin-weather/fokin-weather
