name: test
on: push

jobs:
  build:
    runs-on: unity
    
    steps:
      - uses: normal111/fokin-weather@master
      - name: Check File
        run: |
          ls
          pwd
          ls -al /actions-runner/_work/fokin-weather/fokin-weather
