name: test
on: push

jobs:
  build:
    name: test build

    runs-on: unity
    steps:
      - name: Hello world
        run: |
          ls
          pwd
          ls -al /actions-runner/_work/fokin-weather/fokin-weather
